// The WMA11/01 October 2025 paper as its PDF actually extracts.
const L = (text) => ({ page: 1, text });

export const LINES = [
  L('Pearson Edexcel International Advanced Level'),
  L('Thursday 9 October 2025'),
  L('Morning (Time: 1 hour 30 minutes) WMA11/01 Paper reference'),
  L('Mathematics'),
  L('Pure Mathematics P1'),
  L('Answer the questions in the spaces provided'),
  L('– there may be more space than you need.'),
  L('There are 10 questions in this question paper. The total mark for this paper is 75.'),

  L('1. The curve C has equation'),
  L('y = 6x2 + 3 x + 5 8   x > 0'),
  L('(a) Find d d y x writing the answer in simplest form.'),
  L('(3)'),
  L('The point P 1 4 5 2 lies on C.'),
  L('(b) Find the equation of the tangent to C at P, writing your answer in the form'),
  L('y = mx + c where m and c are integers.'),
  L('(3)'),
  L('Question 1 continued'),
  L('(Total for Question 1 is 6 marks)'),

  L('2. Find'),
  L('( ) x x   ( ) x  3 2 5 2 d'),
  L('writing the answer in simplest form.'),
  L('(5)'),
  L('Question 2 continued'),
  L('(Total for Question 2 is 5 marks)'),

  L('3. The sides of a triangle are in the ratio 2:4:5'),
  L('(a) Find the size of the largest angle of the triangle, in degrees, to one decimal place.'),
  L('(2)'),
  L('Given that the area of the triangle is 140cm 2'),
  L('(b) find the length of the shortest side, in cm, to one decimal place.'),
  L('(3)'),
  L('Question 3 continued'),
  L('(Total for Question 3 is 5 marks)'),

  L('4. In this question you must show all stages of your working.'),
  L('Solutions relying on calculator technology are not acceptable.'),
  L('(i) Using the laws of indices, solve'),
  L('3 1 9 27 2 5 p'),
  L('(3)'),
  L('(ii) Find the real roots of the equation'),
  L('x x 2 2 1 36 4'),
  L('(4)'),
  L('Question 4 continued'),
  L('(Total for Question 4 is 7 marks)'),

  // Question 5 opens with the number alone — Figure 1 follows it.
  L('5.'),
  L('R O M P C y x l'),
  L('Figure 1'),
  L('In this question you must show all stages of your working.'),
  L('(a) Express 2x 2 – 16x + 50 in the form'),
  L('a(x + b) 2 + c'),
  L('where a, b and c are constants to be found.'),
  L('(3)'),
  L('Figure 1 shows a sketch of the curve C with equation y = 2x 2 – 16x + 50'),
  L('M is the minimum point on C'),
  L('line l passes through the origin and intersects C at the points M and P'),
  L('(b) find, using algebra and showing your working, the x coordinate of P.'),
  L('(5)'),
  L('The region R is shown shaded in Figure 1.'),
  L('(c) Use inequalities to fully define R.'),
  L('(2)'),
  L('Question 5 continued'),
  L('(Total for Question 5 is 10 marks)'),

  L('6. (a) Sketch the graph of the curve C with equation'),
  L('y 4k x 2k'),
  L('where k is a positive constant.'),
  L('On your sketch show'),
  L('the coordinates of any points where C cuts the coordinate axes'),
  L('the equation of the vertical asymptote to C'),
  L('(4)'),
  L('The straight line l has equation'),
  L('y = 6 – 2x'),
  L('Given that there is at least one point of intersection between l and C,'),
  L('(b) find the range of possible values of k.'),
  L('(5)'),
  L('Question 6 continued'),
  L('(Total for Question 6 is 9 marks)'),

  // Question 7 opens with the number alone — Figure 2 follows it.
  L('7.'),
  L('Q R O S P T'),
  L('Figure 2'),
  L('Figure 2 shows the plan view of a design for a swimming pool.'),
  L('The design consists of a sector POS of a circle centre O joined to a major sector'),
  L('QORTQ of a different circle, also with centre O.'),
  L('angle POS is 1.65 radians'),
  L('the area of sector POS is 30m 2'),
  L('PQ = 2.8m'),
  L('(a) show that, to 3 significant figures, OQ = 8.83m'),
  L('(3)'),
  L('(b) Find the total surface area of the swimming pool in m2 to the nearest integer.'),
  L('(3)'),
  L('(c) Find the total perimeter of the swimming pool in metres to 2 significant figures.'),
  L('(3)'),
  L('Question 7 continued'),
  L('(Total for Question 7 is 9 marks)'),

  L('8. In this question you must show all stages of your working.'),
  L('A curve has equation y = f(x), x > 0'),
  L('f ( x x ) , x 2 k 8 2 where k is a constant'),
  L('the equation of the tangent to the curve at x = 2 is y x   5 3 2'),
  L('(a) find the exact value of k.'),
  L('(2)'),
  L('(b) Find an equation of the normal to the curve at x = 2'),
  L('(2)'),
  L('(c) Find f(x), writing your answer in simplest form.'),
  L('(4)'),
  L('Question 8 continued'),
  L('(Total for Question 8 is 8 marks)'),

  // Question 9 opens with the number alone — Figure 3 follows it.
  L('9.'),
  L('y P –2 2 4 –4 – O x 2'),
  L('Figure 3'),
  L('Figure 3 shows a sketch of part of the graph of the trigonometric function with'),
  L('equation y = f(x)'),
  L('(a) Write down an expression for f(x)'),
  L('(2)'),
  L('The point P lies on y = f(x) and is shown in Figure 3.'),
  L('(b) State the coordinates of the point to which P is transformed when the graph of'),
  L('y = f(x) is transformed to the graph with equation'),
  L('(i) f 6 y x'),
  L('(2)'),
  L('(ii) y x   1 2 f ( )'),
  L('(2)'),
  L('Question 9 continued'),
  L('(Total for Question 9 is 6 marks)'),

  // Question 10 opens with the number alone — Figure 4 follows it.
  L('10.'),
  L('R Q O P C y x l'),
  L('Figure 4'),
  L('Figure 4 shows a sketch of the curve C with equation'),
  L('y x   2 x x   1 2 2 5 3 2'),
  L('The line l is the normal to C at the point P where x = 0'),
  L('The line l also intersects C at points Q and R as shown in Figure 4.'),
  L('(a) Find, using algebra, the x coordinate of point Q.'),
  L('(6)'),
  L('The point T lies on C.'),
  L('the tangent to C at T is parallel to l'),
  L('the x coordinate of T is positive'),
  L('(b) find, using algebra, the exact x coordinate of T.'),
  L('(4)'),
  L('Question 10 continued'),
  L('(Total for Question 10 is 10 marks)'),
  L('TOTAL FOR PAPER IS 75 MARKS'),
];
